config/routes.rb
Rails.application.routes.draw do


  root 'welcome#homepage'

  get 'tacos' => 'welcome#homepage', as: :tacos
  post 'tacos' => 'tacos#create'
  get 'tacos/new' => 'tacos#new', as: :new_taco
  get 'tacos/:id' => 'tacos#show', as: :taco
  get 'tacos/:id/edit' => 'tacos#edit', as: :edit_taco
  delete 'tacos/:id' => 'tacos#delete'
  patch 'tacos/:id' => 'tacos#update'

  get 'tacos/:taco_id/sharing/new' => 'sharing#new', as: :new_share
  post 'tacos/:taco_id/sharing' => 'sharing#create', as: :create_share
  get 'sharing/thanks' => 'sharing#thanks', as: :thanks_for_sharing

  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create'
  delete 'sign_in' => 'sessions#delete'

  get 'registration' => 'users#new', as: :new_user
  post 'registration' => 'users#create', as: :create_user

  get 'passwords/new' => 'passwords#new', as: :new_password
  post 'passwords' => 'passwords#create', as: :create_password
  get 'passwords/reset/:token' => 'passwords#reset', as: :reset_password
  patch 'passwords/reset/:token' => 'passwords#update'


  get 'users' => 'users#index', as: :users
  get 'entourage' => 'users#following', as: :following
  post 'follow/:user_id' => 'users#follow', as: :follow
  post 'unfollow/:user_id' => 'users#unfollow', as: :unfollow

  get 'feed' => 'tacos#feed', as: :feed

  get 'tacos/:taco_id/charges/new' => 'charges#new', as: :new_charge
  post 'tacos/:taco_id/charges' => 'charges#create', as: :process_charge

  get 'api/tacos' => 'api/tacos#index', as: :api_tacos
  get 'api/tacos/:id' => 'api/tacos#show', as: :api_taco
  post 'api/tacos' => 'api/tacos#create'
  patch 'api/tacos/:id' => 'api/tacos#update'
  put 'api/tacos/:id' => 'api/tacos#update'
  delete 'api/tacos/:id' => 'api/tacos#delete'

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :username, presence: true
  validates :email, presence: true, uniqueness: true
  has_secure_password
  has_many :tacos
  acts_as_follower
  acts_as_followable

  # def timeline
  #   user_ids = following_users.pluck(:id)
  #   user_ids.push(id)
  #   Taco.where(user_id: user_ids).order("created_at DESC")
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where("id != ?", @current_user.id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.email = params[:user][:email]
    @user.username = params[:user][:username]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.save
      # we should also sign them in
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Welcome!"
    else
      render :new
    end
  end

  def following
    @users = @current_user.following_users
  end

  def follow
    # do the thing
    user = User.find_by! id: params[:user_id]
    @current_user.follow(user)
    redirect_to users_path, notice: "✅✅"
  end

  def unfollow
    user = User.find_by! id: params[:user_id]
    @current_user.stop_following(user)
    redirect_to users_path, notice: "👻👻"
  end
end

app/views/users/following.html.erb
<div class="page-header">
  <h1>People You Follow</h1>
</div>


<div class="list-group">
  <% @users.each do |user| %>
    <div class="list-group-item">
      <%= user.username %>
    </div>
  <% end %>

</div>

app/views/users/index.html.erb
<div class="page-header">
  <h1>All Users</h1>
</div>

<div class="list-group">
  <% @users.each do |user| %>
    <div class="list-group-item">
      <%= user.username %> -
        <% if @current_user.following?(user) %>
          <%= link_to "Ghost #{user.username}", unfollow_path(user_id: user.id), method: :post, class: "btn btn-primary" %>
        <% else %>
          <%= link_to "Follow #{user.username}", follow_path(user_id: user.id), method: :post, class: "btn btn-primary" %>
        <% end %>
    </div>
  <% end %>

</div>

app/views/users/new.html.erb
<div class="page-header">
  <h1>Hi! Sign Up!</h1>
</div>

<% if @user.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <% @user.errors.full_messages.each do |msg| %>
      <%= msg %><br>
    <% end %>
  </div>
<% end %>

<div class="well">


<%= form_for @user, url: create_user_path do |f| %>
  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Sign Up", class: "btn btn-lg btn-primary" %>
  </div>

<% end %>


</div>