config/routes.rb
Rails.application.routes.draw do


  root 'welcome#homepage'

  get 'tacos' => 'welcome#homepage', as: :tacos
  post 'tacos' => 'tacos#create'
  get 'tacos/new' => 'tacos#new', as: :new_taco
  get 'tacos/:id' => 'tacos#show', as: :taco
  get 'tacos/:id/edit' => 'tacos#edit', as: :edit_taco
  delete 'tacos/:id' => 'tacos#delete'
  patch 'tacos/:id' => 'tacos#update'

  get 'tacos/:taco_id/sharing/new' => 'sharing#new', as: :new_share
  post 'tacos/:taco_id/sharing' => 'sharing#create', as: :create_share
  get 'sharing/thanks' => 'sharing#thanks', as: :thanks_for_sharing

  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create'
  delete 'sign_in' => 'sessions#delete'

  get 'registration' => 'users#new', as: :new_user
  post 'registration' => 'users#create', as: :create_user

  get 'passwords/new' => 'passwords#new', as: :new_password
  post 'passwords' => 'passwords#create', as: :create_password
  get 'passwords/reset/:token' => 'passwords#reset', as: :reset_password
  patch 'passwords/reset/:token' => 'passwords#update'


  get 'users' => 'users#index', as: :users
  get 'entourage' => 'users#following', as: :following
  post 'follow/:user_id' => 'users#follow', as: :follow
  post 'unfollow/:user_id' => 'users#unfollow', as: :unfollow

  get 'feed' => 'tacos#feed', as: :feed

  get 'tacos/:taco_id/charges/new' => 'charges#new', as: :new_charge
  post 'tacos/:taco_id/charges' => 'charges#create', as: :process_charge

  get 'api/tacos' => 'api/tacos#index', as: :api_tacos
  get 'api/tacos/:id' => 'api/tacos#show', as: :api_taco
  post 'api/tacos' => 'api/tacos#create'
  patch 'api/tacos/:id' => 'api/tacos#update'
  put 'api/tacos/:id' => 'api/tacos#update'
  delete 'api/tacos/:id' => 'api/tacos#delete'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def homepage
    q = Taco.all
    q = q.where("name ILIKE ?", "%#{params[:query]}%") if params[:query].present?
    q = q.where("price >= ?", params[:price_min].to_f) if params[:price_min].present?
    q = q.where("price <= ?", params[:price_max].to_f) if params[:price_max].present?
    @tacos = q
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/homepage.html.erb
<div class="page-header">
  <h1>Welcome to TacoStand <small>Where we stand for tacos!</small></h1>
</div>

  <h2>Tacos</h2>
  <button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="left" title="Tooltip on left">Tooltip on left</button>
  
  <p class="text-right">
    <%= link_to 'New Taco', new_taco_path, class: "text-right btn btn-default" %>
  </p>

  <%= form_tag root_path, method: :get, class: "well" do %>

    <div class="row">
      <div class="col-sm-3">
        <div class="form-group">
          <%= label_tag :query, "Search for: "%>
          <%= text_field_tag :query, params[:query], class: 'form-control', placeholder: "Search Text"%>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="form-group">
          <%= label_tag :price_min, "Minimum Price"%>
          <%= select_tag :price_min,  options_for_select(0..20), prompt: "Please select a minimum Price", class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="form-group">
          <%= label_tag :price_max, "Maximum Price"%>
          <%= select_tag :price_max,  options_for_select(0..20), prompt: "Please select a maximum Price", class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="form-group">
          <br>
          <%= submit_tag "Search", class: "btn btn-default btn-block btn-lg" %>
        </div>
      </div>
    </div>





  <% end %>

  <% if @tacos.empty? %>
  <div class="alert alert-info">
    No Tacos Found
  </div>
  <% end %>


  <% @tacos.each do |taco| %>
    <div class="col-xs-4">
      <%= link_to taco_path(id: taco.id) do %>
        <div class="thumbnail">
          <%= image_tag taco.photo_url, class: "taco-thumb" %>
          <div class="caption">
            <%= taco.name %> - <%= number_to_currency taco.price %>
          </div>
        </div>
      <% end %>
    </div>

  <% end %>