config/routes.rb
Rails.application.routes.draw do


  root 'welcome#homepage'

  get 'tacos' => 'welcome#homepage', as: :tacos
  post 'tacos' => 'tacos#create'
  get 'tacos/new' => 'tacos#new', as: :new_taco
  get 'tacos/:id' => 'tacos#show', as: :taco
  get 'tacos/:id/edit' => 'tacos#edit', as: :edit_taco
  delete 'tacos/:id' => 'tacos#delete'
  patch 'tacos/:id' => 'tacos#update'

  get 'tacos/:taco_id/sharing/new' => 'sharing#new', as: :new_share
  post 'tacos/:taco_id/sharing' => 'sharing#create', as: :create_share
  get 'sharing/thanks' => 'sharing#thanks', as: :thanks_for_sharing

  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create'
  delete 'sign_in' => 'sessions#delete'

  get 'registration' => 'users#new', as: :new_user
  post 'registration' => 'users#create', as: :create_user

  get 'passwords/new' => 'passwords#new', as: :new_password
  post 'passwords' => 'passwords#create', as: :create_password
  get 'passwords/reset/:token' => 'passwords#reset', as: :reset_password
  patch 'passwords/reset/:token' => 'passwords#update'


  get 'users' => 'users#index', as: :users
  get 'entourage' => 'users#following', as: :following
  post 'follow/:user_id' => 'users#follow', as: :follow
  post 'unfollow/:user_id' => 'users#unfollow', as: :unfollow

  get 'feed' => 'tacos#feed', as: :feed

  get 'tacos/:taco_id/charges/new' => 'charges#new', as: :new_charge
  post 'tacos/:taco_id/charges' => 'charges#create', as: :process_charge

  get 'api/tacos' => 'api/tacos#index', as: :api_tacos
  get 'api/tacos/:id' => 'api/tacos#show', as: :api_taco
  post 'api/tacos' => 'api/tacos#create'
  patch 'api/tacos/:id' => 'api/tacos#update'
  put 'api/tacos/:id' => 'api/tacos#update'
  delete 'api/tacos/:id' => 'api/tacos#delete'

end

app/models/taco.rb
class Taco < ActiveRecord::Base

  belongs_to :user
  validates :price, numericality: {less_than_or_equal_to: 7}
  validates :user, presence: true
  validates :photo_url, presence: true
  validates :name, presence: true

  scope :timeline_for_user, -> (user) {
    user_ids = user.following_users.pluck(:id)
    user_ids.push(user.id)
    where(user_id: user_ids).order("created_at DESC")
  }

  def price_in_cents
    (price * 100).to_i
  end
end

app/controllers/api/tacos_controller.rb
class Api::TacosController < ApplicationController

  before_action do
    request.format = :json
  end

  protect_from_forgery with: :null_session

  def index
    q = Taco.all
    q = q.where("name ILIKE ?", "%#{params[:query]}%") if params[:query].present?
    q = q.where("price >= ?", params[:price_min].to_f) if params[:price_min].present?
    q = q.where("price <= ?", params[:price_max].to_f) if params[:price_max].present?
    @tacos = q
    # render json: @tacos
  end

  def show
    @taco = Taco.find_by id: params[:id]
    # render json: @taco
  end

  def create
    @taco = Taco.new
    @taco.name = params[:taco][:name]
    @taco.price = params[:taco][:price]
    @taco.photo_url = params[:taco][:photo_url]
    @taco.user = User.first # for now, until we can authenticate
    if @taco.save
      render :show, status: 201 #created
    else
      render json: {errors: @taco.errors}, status: 422 #error
    end
  end

  def update
    @taco = Taco.find_by id: params[:id]
    if @taco.update params.require(:taco).permit(:name, :price, :photo_url)
      render :show, status: 200 #created
    else
      render json: {errors: @taco.errors}, status: 422 #error
    end
  end

  def delete
    @taco = Taco.find_by id: params[:id]
    @taco.destroy
    render json: {ok: true}, status: 200
  end
end

app/controllers/tacos_controller.rb
class TacosController < ApplicationController

  before_action except: :show do
    if @current_user.nil?
      redirect_to sign_in_path, alert: "Please Sign In"
    end
  end

  def feed
    @tacos = Taco.timeline_for_user(@current_user)
  end

  def show
    @taco = Taco.find_by id: params[:id]
  end

  def new
    @taco = Taco.new
  end

  def create
    @taco = Taco.new
    @taco.name = params[:taco][:name]
    @taco.price = params[:taco][:price]
    @taco.photo_url = params[:taco][:photo_url]
    @taco.user = @current_user

    if @taco.save
      redirect_to root_path, notice: "Taco Created!"
    else
      render :new
    end
  end

  def edit
    @taco = @current_user.tacos.find_by! id: params[:id]
  end

  def update
    @taco = @current_user.tacos.find_by! id: params[:id]
    @taco.name = params[:taco][:name]
    @taco.price = params[:taco][:price]
    @taco.photo_url = params[:taco][:photo_url]
    if @taco.save
      redirect_to root_path, notice: "Taco Updated!"
    else
      render :edit
    end

  end

  def delete
    @taco = @current_user.tacos.find_by! id: params[:id]
    @taco.destroy
    redirect_to root_path, notice: "Taco Obliterated!"
  end
end

app/helpers/tacos_helper.rb
module TacosHelper
end

app/views/tacos/_form.html.erb
<% if @taco.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <% @taco.errors.full_messages.each do |msg| %>
      <%= msg %><br>
    <% end %>
  </div>
<% end %>

<div class="well">

<%= form_for @taco do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :photo_url %>
    <%= f.text_field :photo_url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address_line_1 %>
    <%= f.text_field :address_line_1, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: "form-control" %>
  </div>

  <div class="row">

    <div class="col-sm-4">
      <div class="form-group">
        <%= f.label :state %>
        <%= f.text_field :state, class: "form-control"  %>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="form-group">
        <%= f.label :zip %>
        <%= f.text_field :zip, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-4">

        <div class="form-group">
          <%= f.label :country %>
          <%= f.text_field :country, class: "form-control" %>
        </div>
    </div>

  </div>








  <div class="form-group">
    <%= f.submit class: "btn btn-lg btn-primary"%>
  </div>
<% end %>
</div>

app/views/tacos/edit.html.erb
<div class="page-header">
  <h1>Update Taco</h1>
</div>

<%= render partial: 'form' %>

app/views/tacos/feed.html.erb
<div class="list-group">
  <% @tacos.each do |taco| %>
    <div class="list-group-item">
      <%= link_to taco.name, taco_path(id: taco.id) %> - By <%= taco.user.username %>
    </div>
  <% end %>

</div>

app/views/tacos/new.html.erb
<div class="page-header">
  <h1>New Taco <small>Thanks!</small></h1>
</div>
<%= render partial: 'form' %>

app/views/tacos/show.html.erb
<div class="page-header">
  <h1><%= @taco.name %></h1>
</div>

<div class="row">
  <div class="col-xs-4">
    <dt>Price</dt>
    <dd>
      <%= number_to_currency @taco.price %>
      <%= link_to 'Buy This Taco', new_charge_path(taco_id: @taco.id) %>
    </dd>
  </div>
  <div class="col-xs-4">
    <dt>User</dt>
    <dd><%= @taco.user.username %></dd>
  </div>
  <div class="col-xs-4">

    <% if @taco.user == @current_user %>
      <%= link_to "Update Taco", edit_taco_path(id: @taco.id), class: 'btn btn-default' %>

      <%= link_to "Delete Taco", taco_path(id: @taco.id), method: :delete, class: "btn btn-danger" %>
    <% end %>

    <%= link_to new_share_path(taco_id: @taco.id), class: "btn btn-success" do %>
      <i class="glyphicon glyphicon-envelope"></i> Share Taco
    <% end %>

  </div>
</div>





<%= image_tag @taco.photo_url %>